name: Docker

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev
  schedule:
    - cron: '0 3 * * *'

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build --no-cache . --file Dockerfile --tag itachi1706/youtube-dl-with-aria2:testing
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
          version: latest
    - name: Make BuildX executable
      run: chmod +x buildx.sh
    - name: Build the Docker images
      run: ./buildx.sh
